# Generated by Django 6.0.1 on 2026-02-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarecord',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
    ]
