# Generated by Django 6.0.1 on 2026-02-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
