# Generated by Django 6.0.1 on 2026-02-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsacceptance',
            name='ip_address',
        ),
    ]
