# Generated by Django 6.0.2 on 2026-03-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_querytask'),
        ('ask', '0003_termsacceptance'),
    ]

    operations = [
    ]
