# Generated by Django 6.0.2 on 2026-03-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_merge_0003_querytask_0003_termsacceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('workflow_id', models.CharField(max_length=255)),
                ('agent_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('workflow_type', models.CharField(choices=[('agent', 'Agent')], default='agent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
