# Generated by Django 6.0.2 on 2026-03-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_conversation_qarecord_conversation'),
        ('ask', '0004_merge_0003_querytask_0003_termsacceptance'),
    ]

    operations = [
    ]
