# Generated by Django 6.0.2 on 2026-03-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_merge_20260304_2256'),
        ('ask', '0005_websiteresource'),
    ]

    operations = [
    ]
