# Generated by Django 6.0.2 on 2026-03-09 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_merge_0005_merge_20260304_2256_0005_simworkflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simworkflow',
            old_name='agent_url',
            new_name='agent_endpoint',
        ),
    ]
