# Generated by Django 6.0.2 on 2026-03-11 18:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_merge_0005_merge_20260304_2256_0005_websiteresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='llm_conversation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
