# Generated by Django 6.0.2 on 2026-03-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_merge_0005_merge_20260304_2256_0005_websiteresource'),
        ('ask', '0007_rename_agent_url_simworkflow_agent_endpoint'),
    ]

    operations = [
    ]
