# Generated by Django 6.0.2 on 2026-03-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_conversation_llm_conversation_id'),
        ('ask', '0008_merge_20260310_1836'),
    ]

    operations = [
    ]
