# Generated by Django 6.0.2 on 2026-03-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0009_merge_20260311_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteresource',
            name='mcp_kb_document_id',
            field=models.IntegerField(blank=True, help_text='Document ID returned by the MCP Knowledge Base.', null=True),
        ),
    ]
