# Generated by Django 6.0.2 on 2026-04-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0011_pdfresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfresource',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('error', 'Error'), ('warning', 'Warning')], default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='pdfresource',
            name='status_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='websiteresource',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('error', 'Error'), ('warning', 'Warning')], default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='websiteresource',
            name='status_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
